CREATE DATABASE ropas;

CREATE TABLE pantalones(
id INT NOT NULL AUTO_INCREMENT,
marca VARCHAR(50) NOT NULL,
talla INT  NOT NULL,
precio DECIMAL NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE camisas(
id INT NOT NULL AUTO_INCREMENT,
marca VARCHAR(50) NOT NULL,
talla INT NOT NULL,
precio DECIMAL NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE chompas(
id INT NOT NULL AUTO_INCREMENT,
marca VARCHAR(50) NOT NULL,
talla INT NOT NULL,
precio DECIMAL NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE zapatos(
id INT NOT NULL AUTO_INCREMENT,
marca VARCHAR(50) NOT NULL,
talla INT NOT NULL,
precio DECIMAL NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE blusas(
id INT NOT NULL AUTO_INCREMENT,
tipoBlusas VARCHAR(50) NOT NULL,
talla INT NOT NULL,
precio DECIMAL NOT NULL,
PRIMARY KEY (id)
);

TRUNCATE TABLE 
